apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  labels:
    app: data-ingestion
  namespace: data-ingestion
spec:
  replicas: 0
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      serviceAccountName: statement-demo
      containers:
      - name: data-ingestion
        image: 837108680928.dkr.ecr.us-east-1.amazonaws.com/data-ingestion:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/application-aws.properties
          name: config
          subPath: application-aws.properties
        resources:
          limits:
            memory: "4Gi"
            cpu: 2
          requests:
            memory: "4Gi"
            cpu: 2
        env:
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=90.0"
        - name: KAFKA_BOOTSTRAP
          valueFrom:
            configMapKeyRef:
              name: kafka
              key: bootstrap
        - name: KAFKA_GROUP_ID
          value: "data-ingestion"
        - name: KAFKA_MAX_POOL_RECORDS
          value: "10000"
        - name: KAFKA_CONCURRENCY
          value: "100"
        - name: KAFKA_TOPIC
          value: "generate"
        - name: ELASTICSEARCH_URIS
          valueFrom:
            configMapKeyRef:
              name: elasticsearch
              key: url
        - name: CLOUDWATCH_NAMESPACE
          value: "statement12"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      volumes:
      - configMap:
          name: application.properties
        name: config
